### ISSUE TITLE
missing from steam workshop?

### ISSUE THREAD

**Issue by thorman123** [AaronCRobinson/ExpandedRoofing#12]
is there a reason why it is gone from the steam workshop? i saw you updated it to b19 but its not on steam anymore... are you planning on re adding it anytime soon?

**Comment by AaronCRobinson** [comment]
I removed it from steam workshop because the community around the mod was persistently growing very nasty and ultimately reducing the quality of my modding work. The license is MIT, so I am happy with others uploading it and essentially taking care of the hassles associated with delivering mods to Steam community. NanoCE of the "Glass & Lighting" mod has reached out about taking parts of the project. They do not seem to be interested as much as keeping the mod in it's entirety but instead cannibalizing the parts related to transparent roofing.  Let me know if you would like to take over managing the mod's releases to steam and I am happy to coordinate with you.

**Comment by CrunchyDuck** [comment]
If you'd be fine with it, I and my partner Oken would be happy to maintain the mod over on Steam's workshop. If you just let us know what it is you'd like us to include (for example, links to your Github page, any kind of disclosure), along with any other directives, we'll look after it without modifying the content.

**Comment by AaronCRobinson** [comment]
I have no requirements for how things are presented on Steam. My requests would be to have a link to the github and an acknowledge for Paradeike/Brrainz work on Harmony (e.g. `Acknowledgements to Pardeike/Brrainz for amazing non-destructive patching library, Harmony.`)

Aside from that, I am happy that someone can take over the steam releases and serving that community.  I am available on steam and you can connect with me (profile link: https://steamcommunity.com/profiles/76561197982352048/myworkshopfiles/?appid=294100) but the main purpose of this would be to relay any information about future updates or any bugs the steam community wishes to pass on to me. Cheers.

**Comment by AaronCRobinson** [comment]
Uploaded by CrunchyDuck: https://steamcommunity.com/sharedfiles/filedetails/?id=1512478761
